// src/components/header.jsx
import React, { Component } from "react";
import tibavaLogo from './../media/tib_tibava_logo_opq.png';

class Header extends Component {
    constructor(props) {
        super(props)
      }

    render() {

        return (
            <div>
                <table border='0px' width="100%">
                    <tbody>
                        <tr>
                        <th width="20%" className="text-align-center"><img className="tibava-logo" src={tibavaLogo} alt="TIB-AV-A" /></th>
                        <th width="65%" className="text-align-center"><h2>Audio Video Analysis</h2>
                            <form class="search" action="">
                              <input type="text" placeholder="Search for publicly available analysis" name="search" />
                              <button type="submit"><i class="fa fa-search"></i> Search</button>
                            </form>
                        </th>
                        <th width="15%" className="text-align-left"></th>
                        </tr>
                    </tbody>
                </table>
            </div>
        );
    }
}

export default Header;

// src/components/Header.vue
<template>
    <div>
        <div class="container">
            <div class="row">
                <div class="col-sm-1">
                    <img class="tibava-logo" src="./../assets/tibava_4.svg" alt="TIB-AV-A" />
                </div>
                <div class="col-sm-3 text-align-left">
                    <h2 class="pd-lg-txt">TIB-AV-A</h2>
                </div>
                <div class="col-sm-8 text-align-left">
                    <h2 class="pd-tittle">TIB AV-Analytics</h2>
                </div>
            </div>
            <!-- <div class="row">
                <div class="col-sm-12">
                    <div class="search pd-search">
                        <input type="text" placeholder="Search for Videos Analysis" name="search" id="search" />
                        <button onClick={this.onSearchClick}><i class="fa fa-search"></i> Search</button>
                    </div>
                </div>
            </div> -->
        </div>
    </div>
</template>

<script>
//import axios from "axios";

export default {
  name: "HeaderView",
  methods: {
      onPlayTimeChange() {
        console.log("the time is anchor2: ");
        //console.log(e.target.currentTime);
      }
  }
}
</script>


<style>
</style>
